### ISSUE TITLE
Questions about inference speed

### ISSUE THREAD

**Issue by Breeze-Zero** [sun-umn/DMPlug#1]
Thank you very much for your work, I just started to learn this kind of problem recently, I tried your method, the effect is good, but the reasoning speed is not satisfactory. in contrast to previous methods that interleave iterative steps in the reverse diffusion process, they usually need to iterate the full step size (1000/≈100 ddim) to achieve good image quality. But your method actually requires 3*5000 iterations(without ES-WMV), which is a nasty experience for the already slow diffusion model approach. As a beginner, I want to ask if this is a common problem with this type of method?

**Comment by HengkangWang** [comment]
Hi Breeze-Zero, thanks for trying our method and asking! This is indeed a valid question and we want to answer it from three aspects.

1. We think that people usually more consider about the running time after achieving comparable performance. However, our method can lead SOTA interleaving methods for both linear and nonlinear IPs---often by large margins (even 6dB in terms of PSNR for some tasks).
2. Based on the current code, you are right, our method with ADAM needs several thousands of iterations. But we do not heavily tune the learning schedule and it is likely that better learning schedules can lead to faster convergency. To further accelerate our method with ADAM, we leave it as future work.
3. Besides ADAM, our method can also be solved by L-BFGS, as reported in our ablation studies, and our method with L-BFGS only needs several hundreds of iterations. Now the L-BFGS version has already been uploaded.

**Comment by Breeze-Zero** [comment]
Thank you for your patient response. @HengkangWang
